### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by pathumego** [pathumego/indesign-sinhala#1]
Turning on World Ready Paragraph Composer would enable sinhala rendering, but still, Rakar, Reph, Yansaya is not rendered. 

An Indesign template file developed by the government press enables Proper Sinhala unicode rendering in Indesign CS 4 up. Like shown here.

![screen shot 2015-06-11 at 8 04 47 pm](https://cloud.githubusercontent.com/assets/6846609/8109650/7ee57fbe-1075-11e5-9e29-8f6809b29909.png)

I can see this file enabling World Ready Composer, selecting custom language `Sinahalese`  

The problem is still I will have to keep opening the same template file to able to use this. And this template is not properly licensed, I was given it because Im in contact with them regarding some fonts. I would like to develop a file, or system that would enable using Sinhala easy. Maybe a simple setup script to copy whatever the needed files and set up scripts. 

- I found this link http://blog.typekit.com/2011/11/04/how-to-enable-more-languages-in-indesign-cs5-5/
But its not clear how to create a custom inx file for a specific language.

Because of this, the whole industry is still using ASCII and old DTP systems.

**Comment by pathumego** [comment]
@miguelsousa Could you help :)

**Comment by miguelsousa** [comment]
@pathumego which InDesign version?

**Comment by pathumego** [comment]
CS5.5  to CS 6 the problem exists. I havent tested on CC

**Comment by miguelsousa** [comment]
What you need is to turn on the World-Ready Composer.

In InDesign CS 6 you can do it through the UI, by selecting one of the options available in the fly-out of the Paragraph panel. See image below.
![paragraphpanelflyout](https://cloud.githubusercontent.com/assets/2119742/8124013/e3eb8cd8-1088-11e5-8bfd-4c5ef4b2fa75.png)

In InDesign CS 5.5 the World-Ready Composer options are not available in the UI. But you can enable the WRC by selecting a text frame, and running this script:
```javascript
//Enable World-Ready Single-line composer in current text selection
app.selection[0].composer = 'Adobe World-Ready Single-line Composer';
```
Save this code in a simple text file, give the file a `.jsx` extension, and place it in the **Scripts Panel** folder. Then in InDesign, open the Scripts panel and run the script by double-clicking on it.

**Comment by pathumego** [comment]
@miguelsousa Thanks, but the problem is still the Rakar, Reph, Yansaya (ක්‍ර ර්‍ව ‍න්‍ය) is not rendered properly. These are using zwj and zwnj to render. The template file I mentioned earlier dose enable rendering these on the fly.

With World Ready Composer Enabled
![screen shot 2015-06-12 at 12 55 19 pm](https://cloud.githubusercontent.com/assets/6846609/8125353/ae3ca688-1102-11e5-8c5a-aba0e56f6ce0.png)


With World Ready Composer Enabled and template file. Everything is rendered properly. You can see it is adding `Sinhalaese` option to the languages. So somehow this template file is enabling the full rendering exceeding the World Ready Composers capabilities.
![screen shot 2015-06-12 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/6846609/8125383/defebd60-1102-11e5-9d03-84343f5a0495.png)


So to reiterate the question :) How do I do something like this?I can email you the file if you have time to take a look :)

PS: I appreciate your support, this is big for industry here.

**Comment by miguelsousa** [comment]
Yes, send me the file to msousa at adobe dot com and I'll have a look.
I only have InDesign CC 2014 installed, so I probably won't be able to exactly reproduce what you're experiencing.

**Comment by miguelsousa** [comment]
OK, I think I figured it out.

In addition to enabling the WRC, you need to apply the language **Sinhala (Sri Lanka)** to the text. InDesign doesn't ship with this language option, so you'll need to [follow the instructions on this page](https://helpx.adobe.com/indesign/kb/add_cs_dictionaries.html). The `<language ISO Code>` for *Sinhala (Sri Lanka)* is `si_LK`.

I just did it on my system and it works. Because I didn't have proper `.aff` and `.dic` files for Sinhala, I copied those files from another language (e.g. `en_US`) and changed their file names to `si_LK.aff` and `si_LK.dic`.

So, read the instructions carefully, make sure you do all the steps, and after relaunching InDesign you should have Sinhala on the languages list. Good luck!

**Comment by miguelsousa** [comment]
The instructions for the just-released InDesign CC 2015 version are very similar. The only difference is that the files to be changed are inside the folder named **Resources** instead of **Plug-Ins**.

**Comment by pathumego** [comment]
@miguelsousa Works like a charm! thank you. I should have tried that before bugging you. Anyway thank you!

**Comment by pathumego** [comment]
@miguelsousa So custom dictionaries are supported from CS 5.5 up right?

**Comment by miguelsousa** [comment]
Yes, InDesign CS 5.5 was the first version to support Hunspell dictionaries.
In InDesign CS 4 and CS 5 it was possible to add more languages to the Languages list —notice I didn't say anything about dictionaries— by using a customized INX file.

**Comment by pathumego** [comment]
AH Yes, thanks!
